import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import Sidebar from '../components/Sidebar/Sidebar';
import { cn } from './myClassNames';
import style from './layout.module.css';
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "OwlTop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={cn(geistSans.variable, style.body)}>
				<Header className={style.header} />
				<Sidebar className={style.sidebar} />
				<main className={style.main}>
					{children}
				</main>
				<Footer className={style.footer} />
			</body>
		</html>
	);
}
