import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import Sidebar from '../components/Sidebar/Sidebar';
import { cn } from './myClassNames';
import { Noto_Sans } from 'next/font/google';
import styles from './layout.module.css';
import "./globals.css";

const notoSans = Noto_Sans({
	weight: ['300', '400', '500', '600', '700'],
	style: ['normal', 'italic'],
	subsets: ['latin'],
	display: 'swap',
	preload: false
});

export const metadata: Metadata = {
	title: "OwlTop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={cn(notoSans.className, styles.body)}>
				<Header className={styles.header} />
				<Sidebar className={styles.sidebar} />
				<main className={styles.main}>
					{children}
				</main>
				<Footer className={styles.footer} />
			</body>
		</html>
	);
}
